import { SignedIn } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ClientOnly from "~/components/ClientOnly";
import Countries from "~/components/Countries";
import Header from "~/components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Clerk Postura</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Clerk Postura
          </h1>
          <h2 className="font-mono text-xl">
            Vercel | Hasura | Postgres | Clerk
          </h2>

          <Link
            href={"/server-side"}
            className="text-xl font-medium underline decoration-black"
          >
            Go to: Server-side
          </Link>
          <SignedIn>
            <ClientOnly>
              <Countries />
            </ClientOnly>
          </SignedIn>
        </div>
      </main>
    </>
  );
};

export default Home;
