import { ApolloClient, HttpLink, InMemoryCache } from "@apollo/client";
import { buildClerkProps, getAuth } from "@clerk/nextjs/server";
import {
  type GetServerSideProps,
  type InferGetServerSidePropsType,
  type NextPage,
} from "next";
import Head from "next/head";
import Header from "~/components/Header";
import { env } from "~/env.mjs";
import { getCountries } from "~/graphql";
import { type Country, type GetCountriesQuery } from "~/types/graphql/graphql";

export const getServerSideProps: GetServerSideProps<{
  countries?: Country[];
}> = async (ctx) => {
  const { getToken } = getAuth(ctx.req);

  const token = await getToken({ template: "hasura" });

  if (!token) {
    console.error("Failed to get token from jwt template");
    return { props: {} };
  }

  const httpLink = new HttpLink({
    uri: env.NEXT_PUBLIC_GRAPHQL_URI,
    headers: {
      authorization: `Bearer ${token}`,
    },
  });

  const client = new ApolloClient({
    link: httpLink,
    cache: new InMemoryCache(),
  });

  const { data } = await client.query<GetCountriesQuery>({
    query: getCountries,
  });
  console.log(data);

  console.log("Clerk props:", buildClerkProps(ctx.req));

  return {
    props: {
      countries: data?.Country.slice(0, 4),
    },
  };
};

const ServerSide: NextPage = ({
  countries,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Server-side rendering</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Server-side rendering
          </h1>
          {countries ? (
            <div className="align-center mt-3 flex h-[150px] w-full max-w-3xl justify-center">
              {countries.map((country) => (
                <div
                  key={country.code}
                  className="m-1 grow rounded-xl border border-gray-500 p-3 text-left text-black decoration-transparent transition-all"
                >
                  <h3 className="text-xl font-semibold">
                    {country.name} {country.emoji}
                  </h3>
                  <p className="text-base">{country.code}</p>
                </div>
              ))}
            </div>
          ) : (
            <p>No countries exist</p>
          )}
        </div>
      </main>
    </>
  );
};

export default ServerSide;
